# This file gives reference hyperparameter settings to train the final released version of VA-VAE.
# We adopt a 3-stage training:
# 1. 100 epochs: Used a large weight=0.5 without margin to fully align the latents with the vision foundation model, 
# improving the VAE-VAE's diffusion generation performance.
# 2. 15 epochs: Adjusted weight=0.5 → 0.1 to enhance reconstruction performance.
# 3. 15 epochs: Modified the margin to 0.5 and 0.25 to further improve reconstruction performance.
# This approach stems from our observation that learning reconstruction is easier than learning alignment. By doing so,
# we can reduce the computational cost of tuning weight and margin, requiring only very short fine-tuning.

ckpt_path: /path/to/ckpt # used for testing only, add your ckpt path if you want to test the model
# weight_init: /path/to/weight_init # 1. None -> 2. 1st stg weight --> 3. 2nd stg weight

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    # hyper-param for vision foundation model alignment
    # --------------------------------------------------
    use_vf: dinov2
    reverse_proj: true        # default: true, project from vae dim --> dinov2 dim
    # --------------------------------------------------
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: # 5001 -> 1 -> 1
        kl_weight: 1.0e-06
        disc_weight: 0.5
        # hyper-param for vision foundation model alignment
        # --------------------------------------------------
        vf_weight: # 0.5-> 0.1 ->0.1
        adaptive_vf: true
        distmat_margin: # 0 -> 0 -> 0.25
        cos_margin: # 0 -> 0 -> 0.5
        # --------------------------------------------------
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8 # batch size per GPU
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: /path/to/imagenet
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        data_root: /path/to/imagenet

lightning:
  trainer:
    devices: 8 # number of GPUs, modify it according to your settings
    num_nodes: 4 # number of nodes, modify it according to your settings
    strategy: ddp_find_unused_parameters_true
    accelerator: gpu
    max_epochs: # 100 -> 15 -> 15
    precision: 32
