# VA-VAE配置文件
# 基于LightningDiT原项目的tokenizer配置

# VA-VAE模型路径 (根级别配置) - 匹配实际下载路径
ckpt_path: "/kaggle/working/pretrained/vavae-imagenet256-f16d32-dinov2.pt"

model:
  target: tokenizer.vavae.VA_VAE
  params:
    embed_dim: 32
    n_embed: 16384
    ddconfig:
      double_z: false
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    # DINOv2对齐配置
    use_dinov2: true
    dinov2_model: "dinov2_vitb14"

    # 训练配置
    monitor: "val/rec_loss"
