# VA-VAE配置文件 - 专门用于DiT训练
# 基于微调训练时的实际配置参数
# 不包含adaptive_vf以避免训练损失爆炸问题

ckpt_path: /kaggle/input/stage3/vavae-stage3-epoch26-val_rec_loss0.0000.ckpt

model:
  base_learning_rate: 2.0e-05  # Stage 3的学习率
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    use_vf: dinov2
    reverse_proj: true
    
    # 使用Stage 3的精确损失配置
    lossconfig:
      target: ldm.modules.losses.contperceptual.LPIPSWithDiscriminator
      params:
        disc_start: 1
        kl_weight: 1.0e-06
        disc_weight: 0.5
        vf_weight: 0.1
        # 不设置adaptive_vf，默认为False
        # adaptive_vf会导致训练损失爆炸
        vf_loss_type: combined_v3
        distmat_margin: 0.25
        cos_margin: 0.5
        disc_num_layers: 3
        disc_in_channels: 3
        perceptual_weight: 1.0  # 重要：启用LPIPS感知损失
        use_actnorm: false
        pp_style: false

    # VA-VAE架构配置
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    
    # 其他必要参数
    ignore_keys: []
    image_key: image
    colorize_nlabels: null
    proj_fix: false
