# DiT-S configuration for micro-Doppler dataset
# Based on official LightningDiT config with minimal modifications

# Data configuration
data:
  data_path: './latents_safetensors/train'  # 训练数据路径
  valid_path: './latents_safetensors/val'   # 验证数据路径
  image_size: 256             # 原始图像大小
  num_classes: 31             # 31个用户作为类别数
  num_workers: 12              # 增加数据加载并行度，适配小批次训练
  
  # Channel-wise normalization (与官方LightningDiT一致)
  latent_norm: true      # 使用channel-wise归一化
  latent_multiplier: 1.0 # 归一化后不需要额外缩放

# VAE configuration (我们的VA-VAE)
vae:
  model_name: 'vavae_f16d32'
  downsample_ratio: 16   # 256x256 -> 16x16 latent

# Model configuration - DiT-S (最小模型，手动添加)
model:
  model_type: 'LightningDiT-S/2'  # S模型，patch_size=2正确配置
  use_qknorm: false               # 官方推荐设置
  use_swiglu: true                # 使用SwiGLU激活
  use_rope: true                  # 使用RoPE位置编码
  use_rmsnorm: true               # 使用RMSNorm
  wo_shift: false                 # 不使用shift
  in_chans: 32                    # VA-VAE的32个通道
  use_checkpoint: false           # 小模型不需要梯度检查点
  class_dropout_prob: 0.15        # 增强CFG正则化（默认0.1→0.15）

# Training configuration
train:
  max_steps: 30000               # 提高上限，依靠早停机制防止过拟合
  global_batch_size: 24           # 平衡过拟合防止和GPU利用率的折中方案
  global_seed: 0
  output_dir: '/kaggle/working/VA-VAE/outputs'
  exp_name: 'dit_s_microdoppler_bs24_balanced'
  ckpt: null                      # DiT-S暂无预训练权重，考虑使用DiT-L+智能初始化
  log_every: 1000                 # 日志频率
  ckpt_every: 2000               # 每2000步评估和保存
  resume: false                   # 不恢复训练
  early_stopping_patience: 5      # 增加耐心值，给模型更多收敛机会

# Optimizer configuration (小批次优化配置)
optimizer:
  lr: 0.0001                      # 小批次适用的学习率
  beta2: 0.99                     # 提高beta2适应更noisy的梯度
  max_grad_norm: 0.5              # 更严格梯度裁剪适应小批次噪声
  weight_decay: 0.005             # 减少权重衰减（小批次已提供正则化）

# Transport configuration (Rectified Flow，与官方一致)
transport:
  path_type: Linear
  prediction: velocity
  loss_weight: null
  sample_eps: null
  train_eps: null
  use_lognorm: true               # 使用lognorm
  use_cosine_loss: true           # 使用余弦损失

# Sampling configuration (推理时使用)
sample:
  mode: ODE
  sampling_method: euler          # 使用euler采样
  atol: 0.000001
  rtol: 0.001
  reverse: false
  likelihood: false
  num_sampling_steps: 300         # 采样步数
  cfg_scale: 10.0                 # 条件生成使用CFG=10.0
  per_proc_batch_size: 4
  cfg_interval_start: 0.11
  timestep_shift: 0.1
