# micro-Doppler条件扩散生成微调配置
# 基于LightningDiT-B预训练模型进行用户条件微调（T4内存优化）

model:
  target: LightningDiT
  params:
    model: "LightningDiT-B/1"    # 使用B模型以适应T4内存限制
    num_users: 31                 # 31个用户 (ID_1 到 ID_31)
    latent_size: 16               # VA-VAE f16: 256/16=16
    in_channels: 32               # VA-VAE f16d32潜空间通道数
    condition_dim: 768            # B模型隐藏维度
    use_ema: true                 # 使用EMA模型提升生成质量
    pretrained_path: "models/lightningdit-b-imagenet256.pt"  # Base模型权重
    xl_pretrained_path: "models/lightningdit-xl-imagenet256-64ep.pt"  # XL备用权重

data:
  target: MicroDopplerLatentDataset
  params:
    data_dir: "/kaggle/input/dataset"  # 数据路径
    batch_size: 4                # T4内存限制，使用更小批次
    num_workers: 2               # 减少CPU负载
    image_size: 256
    val_split: 0.2               # 20%验证集
    use_latent_cache: true       # 使用预计算的潜空间表示

trainer:
  precision: "16-mixed"          # FP16混合精度训练
  max_epochs: 25                 # 总训练轮数
  check_val_every_n_epoch: 1     # 每轮验证一次
  gradient_clip_val: 1.0         # 梯度裁剪
  accumulate_grad_batches: 4     # 梯度累积，有效batch_size=16
  log_every_n_steps: 20          # 日志频率
  enable_progress_bar: true
  enable_model_summary: false
  sample_every_n_epochs: 5       # 每5轮生成样本

optimizer:
  target: torch.optim.AdamW
  params:
    lr: 5.0e-5                   # B模型适用的学习率
    weight_decay: 0.01           # 标准权重衰减
    betas: [0.9, 0.95]           # Adam beta参数

scheduler:
  target: torch.optim.lr_scheduler.CosineAnnealingLR
  params:
    T_max: 25                    # 匹配max_epochs
    eta_min: 1.0e-7              # 最小学习率

# 训练策略
training:
  early_stopping:
    patience: 5                  # 早停耐心值
    min_delta: 0.001             # 最小改进阈值
  
  ema:
    enabled: true                # 启用EMA
    decay: 0.9999                # EMA衰减率
  
  memory_optimization:
    gradient_checkpointing: false  # B模型不需要
    mixed_precision: true         # FP16训练
    batch_size: 4                 # 小批次
    gradient_accumulation: 4      # 梯度累积

# 扩散模型配置
diffusion:
  num_timesteps: 1000           # 扩散步数
  path_type: "Linear"           # 线性扩散路径
  prediction: "velocity"        # 预测速度
  sampling:
    method: "ddim"              # DDIM采样
    steps: 50                   # 采样步数
    eta: 0.0                    # 确定性采样
    guidance_scale: 2.0         # CFG强度

# 实验记录
experiment:
  name: "microdoppler_dit_b"
  description: "micro-Doppler条件生成with LightningDiT-B"
  tags: ["microdoppler", "dit-b", "vavae", "conditional"]
  output_dir: "outputs"
  save_best_only: true
