# VA-VAE微调 - 阶段1: DINOv2对齐训练（自定义数据）
# 100 epochs: 使用大权重weight=0.5，无margin，专注于与视觉基础模型对齐

# 预训练模型路径
weight_init: models/vavae-imagenet256-f16d32-dinov2.pt

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    # 视觉基础模型对齐参数
    use_vf: dinov2
    reverse_proj: true        # 从vae维度投影到dinov2维度
    
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 5001        # 阶段1: 延迟判别器启动
        kl_weight: 1.0e-06
        disc_weight: 0.5
        # 视觉基础模型对齐参数
        vf_weight: 0.5          # 阶段1: 大权重专注对齐
        adaptive_vf: true
        distmat_weight: 1.0     # 距离矩阵权重
        cos_weight: 1.0         # 余弦相似度权重
        distmat_margin: 0       # 阶段1: 无margin
        cos_margin: 0           # 阶段1: 无margin
        
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4
    wrap: false
    train:
      target: custom_data_loader.CustomImageTrain
      params:
        data_root: /kaggle/input/dataset
        size: 256
    validation:
      target: custom_data_loader.CustomImageValidation
      params:
        data_root: /kaggle/input/dataset
        size: 256

lightning:
  trainer:
    benchmark: True
    max_epochs: 100
    accumulate_grad_batches: 2
    strategy: ddp
    devices: 2
    precision: 16
  callbacks:
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        dirpath: logs/stage1_custom/checkpoints
        filename: '{epoch:06}'
        verbose: True
        save_last: True
        monitor: val/rec_loss
        save_top_k: -1
        every_n_train_steps: 5000
