# VA-VAE微调 - 阶段3: Margin优化训练
# 15 epochs: 修改margin为0.5和0.25，进一步提升重建性能

# 阶段2训练结果路径 - 请根据实际checkpoint路径修改
weight_init: checkpoints/stage2_reconstruction/last.ckpt

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    # 视觉基础模型对齐参数
    use_vf: dinov2
    reverse_proj: true        # 从vae维度投影到dinov2维度
    
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 1           # 阶段3: 立即启动判别器
        kl_weight: 1.0e-06
        disc_weight: 0.5
        # 视觉基础模型对齐参数
        vf_weight: 0.1          # 阶段3: 保持低权重
        adaptive_vf: true
        distmat_weight: 1.0     # 距离矩阵权重
        cos_weight: 1.0         # 余弦相似度权重
        distmat_margin: 0.25    # 阶段3: 添加距离margin
        cos_margin: 0.5         # 阶段3: 添加余弦margin
        
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8              # 根据GPU内存调整
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        config:
          size: 256
          degradation: pil_nearest
    validation:
      target: ldm.data.imagenet.ImageNetValidation  
      params:
        config:
          size: 256
          degradation: pil_nearest

lightning:
  find_unused_parameters: false
  modelcheckpoint:
    params:
      every_n_train_steps: 2000
      save_top_k: -1
      monitor: null
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        max_images: 4
        increase_log_steps: False
        log_first_step: False
        log_images_kwargs:
          use_ema_scope: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 4
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]
          ddim_steps: 50

  trainer:
    benchmark: True
    val_check_interval: 2000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    max_epochs: 15             # 阶段3: 15 epochs
    gpus: 2                    # 双GPU训练
    strategy: ddp
