# VA-VAE微调配置 - 基于官方单阶段方法
# 在预训练模型基础上微调，适配自定义micro-Doppler数据集

# 预训练模型路径 - 微调的关键
weight_init: models/vavae-imagenet256-f16d32-dinov2.pt

model:
  base_learning_rate: 1.0e-05  # 进一步降低学习率防止FP16数值问题
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    # 视觉基础模型对齐参数 - 与官方完全一致
    use_vf: dinov2
    reverse_proj: true        # 从vae维度投影到dinov2维度
    
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 5001
        kl_weight: 1.0e-05     # 增大KL权重改善潜空间正则化
        disc_weight: 0.5
        # Stage 1微调参数 - 对齐阶段（修复NaN问题）
        vf_weight: 0.5          # Stage 1: 0.5（不是0.1）
        adaptive_vf: true
        distmat_weight: 1.0
        cos_weight: 1.0
        distmat_margin: 0.0     # Stage 1: 无margin
        cos_margin: 0.0         # Stage 1: 无margin
        
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4           # 减小batch_size以节省内存
    num_workers: 2          # 减少worker数量
    wrap: true              # 官方设置为true（不是false）
    train:
      target: custom_data_loader.CustomImageTrain
      params:
        data_root: /kaggle/input/dataset
        size: 256
    validation:
      target: custom_data_loader.CustomImageValidation
      params:
        data_root: /kaggle/input/dataset
        size: 256

lightning:
  find_unused_parameters: false
  modelcheckpoint:
    params:
      every_n_train_steps: 2500    # 更频繁保存（约每20个epoch）
      save_top_k: 1                 # 只保留最好的1个模型
      monitor: val/rec_loss         # 基于验证损失选择最佳模型
      mode: min                     # 损失越小越好
      save_last: false              # 不保存最新模型，只保存最佳
      verbose: true                 # 显示保存信息
      filename: 'vavae-best-{epoch:02d}-{val_rec_loss:.4f}'
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2500       # 更频繁生成样本图像
        max_images: 8               # 增加样本图像数量
        clamp: true

  trainer:
    devices: 2              # Kaggle双GPU
    num_nodes: 1            # 单节点（Kaggle环境）
    strategy: ddp_find_unused_parameters_true   # 启用未使用参数检查（VA-VAE必需）
    accelerator: gpu
    max_epochs: 39          # 保守轮数（假设每轮都验证）
    precision: 16           # 回到FP16提高效率，配合其他稳定化措施
    benchmark: true
    val_check_interval: 3190    # 每5个epoch验证一次 (5 * 638 steps)
    num_sanity_val_steps: 0     # 跳过sanity check避免问题
    accumulate_grad_batches: 4  # 增加梯度累积提高稳定性
    log_every_n_steps: 50       # 每50步记录一次
    enable_progress_bar: true   # 重新启用默认进度条以确保稳定性
    enable_model_summary: false # 禁用模型概要避免问题
    enable_checkpointing: true  # 启用检查点保存
    # 启用logger显示训练结果
    logger: true                # 启用logger显示训练和验证结果
    profiler: null              # 禁用profiler
